In [66]:
import pandas as pd

In [67]:
df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/refs/heads/master/adult-all.csv', header=None)

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       48842 non-null  int64
 1   1       48842 non-null  str
 2   2       48842 non-null  int64
 3   3       48842 non-null  str
 4   4       48842 non-null  int64
 5   5       48842 non-null  str
 6   6       48842 non-null  str
 7   7       48842 non-null  str
 8   8       48842 non-null  str
 9   9       48842 non-null  str
 10  10      48842 non-null  int64
 11  11      48842 non-null  int64
 12  12      48842 non-null  int64
 13  13      48842 non-null  str
 14  14      48842 non-null  str
dtypes: int64(6), str(9)
memory usage: 5.6 MB

In [69]:
df.drop(columns=3, inplace=True)

In [70]:
df

,0,1,2,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K
48838,64,?,321403,9,Widowed,?,Other-relative,Black,Male,0,0,40,United-States,<=50K
48839,38,Private,374983,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
48840,44,Private,83891,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K
48841,35,Self-emp-inc,182148,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K

In [71]:
column = ['age', 'workclass', 'fnlwgt', 'num_edu', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'work-hour-week', 'country', 'income']

In [72]:
df.columns = column
df['workclass'].unique()
df[df['workclass'] == '?']
(df == '?').sum()

age                  0
workclass         2799
fnlwgt               0
num_edu              0
marital-status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
work-hour-week       0
country            857
income               0
dtype: int64

In [73]:
2809/len(df)

0.05751197739650301

In [74]:
#workclass
df['workclass'] = df['workclass'].apply(lambda x: 'unknown' if x == '?' else x)

In [75]:
(df == '?').sum()

age                  0
workclass            0
fnlwgt               0
num_edu              0
marital-status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
work-hour-week       0
country            857
income               0
dtype: int64

In [76]:
df['occupation'] = df['occupation'].apply(lambda x: 'unknown' if x == '?' else x)

In [77]:
(df == '?').sum()

age                 0
workclass           0
fnlwgt              0
num_edu             0
marital-status      0
occupation          0
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
work-hour-week      0
country           857
income              0
dtype: int64

In [78]:
df['country'].value_counts()

# df[df['country'] == '?'] = pd.NA

country
United-States                 43832
Mexico                          951
?                               857
Philippines                     295
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Guatemala                        88
Poland                           87
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Greece                           49
Nicaragua                        49
Peru                             46
Ecuador                          45
France                           38
Ireland                          37
Thailand                         30
Hong                             30
Cambodia                         28
Trinadad&Tobago                  27
Laos                             23
Yugoslavia                       23
Outlying-US(Guam-USVI-etc)       23
Scotland                         21
Honduras                         20
Hungary                          19
Holand-Netherlands                1
Name: count, dtype: int64

In [79]:
df['country'] = df['country'].apply(lambda x: 'United-States' if x =='?' else x)

In [80]:
df['country'].value_counts()

country
United-States                 44689
Mexico                          951
Philippines                     295
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Guatemala                        88
Poland                           87
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Greece                           49
Nicaragua                        49
Peru                             46
Ecuador                          45
France                           38
Ireland                          37
Thailand                         30
Hong                             30
Cambodia                         28
Trinadad&Tobago                  27
Laos                             23
Yugoslavia                       23
Outlying-US(Guam-USVI-etc)       23
Scotland                         21
Honduras                         20
Hungary                          19
Holand-Netherlands                1
Name: count, dtype: int64

In [81]:
(df == '?').sum()

age               0
workclass         0
fnlwgt            0
num_edu           0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
work-hour-week    0
country           0
income            0
dtype: int64

In [82]:
#cek missing value
df[df['age'].isnull()].index
df.drop(df[df['age'].isnull()].index, inplace=True)

In [83]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
num_edu           0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
work-hour-week    0
country           0
income            0
dtype: int64

In [84]:
y = df['income']

In [85]:
y

0        <=50K
1        <=50K
2        <=50K
3        <=50K
4        <=50K
         ...
48837    <=50K
48838    <=50K
48839    <=50K
48840    <=50K
48841     >50K
Name: income, Length: 48842, dtype: str

In [86]:
df.head()

,age,workclass,fnlwgt,num_edu,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,work-hour-week,country,income
0,39,State-gov,77516,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [87]:
feature = ['age', 'workclass', 'num_edu', 'occupation', 'capital-gain', 'capital-loss', 'work-hour-week', 'country']

In [88]:
X = df[feature]

In [89]:
X

,age,workclass,num_edu,occupation,capital-gain,capital-loss,work-hour-week,country
0,39,State-gov,13,Adm-clerical,2174,0,40,United-States
1,50,Self-emp-not-inc,13,Exec-managerial,0,0,13,United-States
2,38,Private,9,Handlers-cleaners,0,0,40,United-States
3,53,Private,7,Handlers-cleaners,0,0,40,United-States
4,28,Private,13,Prof-specialty,0,0,40,Cuba
...,...,...,...,...,...,...,...,...
48837,39,Private,13,Prof-specialty,0,0,36,United-States
48838,64,unknown,9,unknown,0,0,40,United-States
48839,38,Private,13,Prof-specialty,0,0,50,United-States
48840,44,Private,13,Adm-clerical,5455,0,40,United-States
48841,35,Self-emp-inc,13,Exec-managerial,0,0,60,United-States

In [90]:
y

0        <=50K
1        <=50K
2        <=50K
3        <=50K
4        <=50K
         ...
48837    <=50K
48838    <=50K
48839    <=50K
48840    <=50K
48841     >50K
Name: income, Length: 48842, dtype: str

In [91]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)

In [92]:
y

array([0, 0, 0, ..., 0, 0, 1], shape=(48842,))

In [93]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [94]:
df['income'].value_counts()

income
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [95]:
X

,age,workclass,num_edu,occupation,capital-gain,capital-loss,work-hour-week,country
0,39,State-gov,13,Adm-clerical,2174,0,40,United-States
1,50,Self-emp-not-inc,13,Exec-managerial,0,0,13,United-States
2,38,Private,9,Handlers-cleaners,0,0,40,United-States
3,53,Private,7,Handlers-cleaners,0,0,40,United-States
4,28,Private,13,Prof-specialty,0,0,40,Cuba
...,...,...,...,...,...,...,...,...
48837,39,Private,13,Prof-specialty,0,0,36,United-States
48838,64,unknown,9,unknown,0,0,40,United-States
48839,38,Private,13,Prof-specialty,0,0,50,United-States
48840,44,Private,13,Adm-clerical,5455,0,40,United-States
48841,35,Self-emp-inc,13,Exec-managerial,0,0,60,United-States

In [96]:
for i in ['workclass', 'occupation', 'country']:
    le = LabelEncoder()
    X['en-', i] = le.fit_transform(X[i])

In [97]:
X

,age,workclass,num_edu,occupation,capital-gain,capital-loss,work-hour-week,country,"(en-, workclass)","(en-, occupation)","(en-, country)"
0,39,State-gov,13,Adm-clerical,2174,0,40,United-States,6,0,38
1,50,Self-emp-not-inc,13,Exec-managerial,0,0,13,United-States,5,3,38
2,38,Private,9,Handlers-cleaners,0,0,40,United-States,3,5,38
3,53,Private,7,Handlers-cleaners,0,0,40,United-States,3,5,38
4,28,Private,13,Prof-specialty,0,0,40,Cuba,3,9,4
...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,13,Prof-specialty,0,0,36,United-States,3,9,38
48838,64,unknown,9,unknown,0,0,40,United-States,8,14,38
48839,38,Private,13,Prof-specialty,0,0,50,United-States,3,9,38
48840,44,Private,13,Adm-clerical,5455,0,40,United-States,3,0,38
48841,35,Self-emp-inc,13,Exec-managerial,0,0,60,United-States,4,3,38

In [98]:
X.drop(columns=['workclass', 'occupation', 'country'], inplace=True)

In [99]:
X

,age,num_edu,capital-gain,capital-loss,work-hour-week,"(en-, workclass)","(en-, occupation)","(en-, country)"
0,39,13,2174,0,40,6,0,38
1,50,13,0,0,13,5,3,38
2,38,9,0,0,40,3,5,38
3,53,7,0,0,40,3,5,38
4,28,13,0,0,40,3,9,4
...,...,...,...,...,...,...,...,...
48837,39,13,0,0,36,3,9,38
48838,64,9,0,0,40,8,14,38
48839,38,13,0,0,50,3,9,38
48840,44,13,5455,0,40,3,0,38
48841,35,13,0,0,60,4,3,38

In [100]:
X.columns

Index([                'age',             'num_edu',        'capital-gain',
              'capital-loss',      'work-hour-week',  ('en-', 'workclass'),
       ('en-', 'occupation'),    ('en-', 'country')],
      dtype='object')

In [101]:
X.columns = X.columns.astype('str')

In [102]:
X

,age,num_edu,capital-gain,capital-loss,work-hour-week,"('en-', 'workclass')","('en-', 'occupation')","('en-', 'country')"
0,39,13,2174,0,40,6,0,38
1,50,13,0,0,13,5,3,38
2,38,9,0,0,40,3,5,38
3,53,7,0,0,40,3,5,38
4,28,13,0,0,40,3,9,4
...,...,...,...,...,...,...,...,...
48837,39,13,0,0,36,3,9,38
48838,64,9,0,0,40,8,14,38
48839,38,13,0,0,50,3,9,38
48840,44,13,5455,0,40,3,0,38
48841,35,13,0,0,60,4,3,38

In [103]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42, stratify=y)

In [104]:
y_train[y_train == 0] #29214
y_train[y_train == 1] #9174

array([1, 1, 1, ..., 1, 1, 1], shape=(9349,))

In [105]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## KKN - K Nearest Neighbour

In [113]:
from sklearn.neighbors import KNeighborsClassifier
import time

knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')

start = time.time()
knn.fit(X_train_scaled, y_train)
time.time()-start

0.04492616653442383

In [107]:
y_pred = knn.predict(X_test_scaled)

In [112]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

accuracy_score(y_test, y_pred)
f1_score(y_test, y_pred)
confusion_matrix(y_test, y_pred)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88      7431
           1       0.63      0.51      0.56      2338

    accuracy                           0.81      9769
   macro avg       0.74      0.71      0.72      9769
weighted avg       0.80      0.81      0.80      9769

### Cross Validation
Stratify Validation / StratifiedKFold

In [114]:
from sklearn.model_selection import StratifiedKFold, GridSearchCV

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [119]:
# set parameter KNN
knn_param = {
    'n_neighbors': [5,10,15],
    'weights': ['uniform', 'distance'],
    'p': [1,2]
}

In [120]:
#hypterparameter tuning
knn = KNeighborsClassifier()
grid_knn = GridSearchCV(
    estimator=knn,
    param_grid=knn_param,
    scoring='accuracy',
    cv=cv,
    n_jobs=-1
)

In [121]:
grid_knn.fit(X_train_scaled, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [5, 10, 15], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [122]:
grid_knn.best_params_

{'n_neighbors': 10, 'p': 1, 'weights': 'uniform'}

In [124]:
grid_knn.best_score_

np.float64(0.8210015620698842)

In [125]:
grid_knn.best_estimator_

KNeighborsClassifier(n_neighbors=10, p=1)

In [126]:
best_knn = grid_knn.best_estimator_

In [127]:
y_pred = best_knn.predict(X_test_scaled)

accuracy_score(y_test, y_pred)

0.8240352134302386

### GaussianNB
probabilitas, main parameter: var_smoothing

In [129]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

#set parameter GNB
gnb_param={
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6]
}

In [130]:
gnb_grid = GridSearchCV(
    estimator=gnb,
    param_grid=gnb_param,
    cv=cv,
    scoring='accuracy',
    n_jobs=-1
)

In [131]:
gnb_grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07, 1e-06]},
             scoring='accuracy')

In [132]:
gnb_grid.best_score_

np.float64(0.7952037756927253)

In [133]:
best_gnb = gnb_grid.best_estimator_

In [134]:
accuracy_score(y_test, best_gnb.predict(X_test_scaled))

0.7979322346197154

### Decision Tree

In [142]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt_param = {
    'max_depth': [5,10,15,20,None],
    'criterion': ['gini', 'entropy'],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1,2,5]
}

In [143]:
dt_grid = GridSearchCV(
    estimator=dt,
    param_grid=dt_param,
    cv=cv,
    scoring='accuracy',
    n_jobs=-1
)

In [144]:
dt_grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 10, 15, 20, None],
                         'min_samples_leaf': [1, 2, 5],
                         'min_samples_split': [2, 5, 10]},
             scoring='accuracy')

In [145]:
dt_grid.best_score_

np.float64(0.8375860444391605)

In [146]:
best_dt = dt_grid.best_estimator_

In [147]:
accuracy_score(y_test, best_dt.predict(X_test_scaled))

0.8393899068481933

### Random Forest
n_estimator -> jumlah tree

In [148]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()

rfc_param = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_leaf': [1,2],
    'min_samples_split': [2, 5] 
}

In [149]:
rfc_grid = GridSearchCV(
    estimator=rfc,
    param_grid=rfc_param,
    cv=cv,
    scoring='accuracy',
    n_jobs=-1
)

In [150]:
rfc_grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [10, 20, None],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             scoring='accuracy')

In [152]:
rfc_grid.best_score_

np.float64(0.8419113257190001)

In [153]:
best_rfc = rfc_grid.best_estimator_

In [154]:
accuracy_score(y_test, best_rfc.predict(X_test_scaled))

0.8434844917596479

### Neural Network (MLP - Multi Layer Perceptron)
hidden_layer_sizes -> jumlah neuron per hidden layer, alpha -> regularisasi (L2)

In [ ]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(max_iter=500, early_stopping=True, random_state=42)

mlp_param = {
    'hidden_layer_sizes': [(32,), (64,), (64, 32)],
    'alpha': [1e-4, 1e-3, 1e-2],
    'learning_rate_init': [1e-3, 1e-2]
}

mlp_grid = GridSearchCV(
    estimator=mlp,
    param_grid=mlp_param,
    cv=cv,
    scoring='accuracy',
    n_jobs=-1
)

mlp_grid.fit(X_train_scaled, y_train)

In [ ]:
print(mlp_grid.best_params_, mlp_grid.best_score_)

best_mlp = mlp_grid.best_estimator_
accuracy_score(y_test, best_mlp.predict(X_test_scaled))

### Neural Network v2 - One-Hot Encoding + fitur tambahan
LabelEncoder bikin kategori jadi angka berurutan (0,1,2..) -> MLP mengira ada urutan. One-hot lebih cocok untuk neural network.
Tambah fitur marital-status & relationship (sebelumnya tidak dipakai). race & sex sengaja tidak dipakai (isu fairness).

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

num_col = ['age', 'num_edu', 'capital-gain', 'capital-loss', 'work-hour-week']
cat_col = ['workclass', 'occupation', 'country', 'marital-status', 'relationship']

X2 = df[num_col + cat_col]

# split sama persis (random_state & stratify sama) -> baris test sama dengan model lain
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y, test_size=.2, random_state=42, stratify=y)

# scaler & encoder di dalam pipeline -> otomatis fit hanya di data train (tiap fold CV juga)
preprocess = ColumnTransformer([
    ('num', StandardScaler(), num_col),
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_col)
])

In [ ]:
mlp2_pipe = Pipeline([
    ('pre', preprocess),
    ('mlp', MLPClassifier(max_iter=500, early_stopping=True, random_state=42))
])

mlp2_param = {
    'mlp__hidden_layer_sizes': [(32,), (64,), (64, 32)],
    'mlp__alpha': [1e-4, 1e-3, 1e-2],
    'mlp__learning_rate_init': [1e-3, 1e-2]
}

mlp2_grid = GridSearchCV(
    estimator=mlp2_pipe,
    param_grid=mlp2_param,
    cv=cv,
    scoring='accuracy',
    n_jobs=-1
)

mlp2_grid.fit(X2_train, y2_train)
print(mlp2_grid.best_params_, mlp2_grid.best_score_)

best_mlp2 = mlp2_grid.best_estimator_
accuracy_score(y2_test, best_mlp2.predict(X2_test))

In [ ]:
# perbandingan adil: RFC dengan fitur & encoding yang sama
rfc2_pipe = Pipeline([
    ('pre', preprocess),
    ('rfc', RandomForestClassifier(**rfc_grid.best_params_, random_state=42, n_jobs=-1))
])
rfc2_pipe.fit(X2_train, y2_train)

for nama, m in {'MLP v2': best_mlp2, 'RFC v2': rfc2_pipe}.items():
    print('Model: ', nama)
    print(classification_report(y2_test, m.predict(X2_test)))

## Evaluasi

In [ ]:
model = {
    'KNN': best_knn, 
    'GNB': best_gnb,
    'DT':  best_dt,
    'RFC': best_rfc,
    'MLP': best_mlp
}

for nama, model in model.items():
    y_pred = model.predict(X_test_scaled)
    print('Model: ', nama)
    print(classification_report(y_test, y_pred))

In [160]:
final_model = best_rfc

In [161]:
final_model

RandomForestClassifier(max_depth=20, min_samples_leaf=2)

In [162]:
import joblib

joblib.dump(final_model, 'fina_rfc.joblib')

['fina_rfc.joblib']

In [163]:
joblib.load('fina_rfc.joblib').predict(X_test_scaled)

array([0, 0, 0, ..., 0, 0, 0], shape=(9769,))

In [165]:
rfc_grid.best_params_
# {'max_depth': 20,
#  'min_samples_leaf': 2,
#  'min_samples_split': 2,
#  'n_estimators': 100}

{'max_depth': 20,
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 100}

In [168]:
pd.DataFrame(X_test_scaled, columns=X.columns).to_csv('X_test_scaled.csv', index=False)
pd.DataFrame(X_train_scaled, columns=X.columns).to_csv('X_train_scaled.csv', index=False)
pd.DataFrame(y_test, columns=['income']).to_csv('y_test.csv', index=False)
pd.DataFrame(y_train, columns=['income']).to_csv('y_train.csv', index=False)

In [169]:
df.to_csv('adult_cleaned.csv')