In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\arifw\Documents\Personal Documents\Jasaraharja Putera\IT General\Pelatihan\Machine Learning\datasets\WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [3]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [4]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [34]:
feature = ['gender','SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'Contract', 'MonthlyCharges', 'TotalCharges']

In [35]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [36]:
X = df[feature]

In [37]:
y = df['Churn']

In [38]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,Contract,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,Month-to-month,29.85,29.85
1,Male,0,No,No,34,One year,56.95,1889.50
2,Male,0,No,No,2,Month-to-month,53.85,108.15
3,Male,0,No,No,45,One year,42.30,1840.75
4,Female,0,No,No,2,Month-to-month,70.70,151.65
...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,One year,84.80,1990.50
7039,Female,0,Yes,Yes,72,One year,103.20,7362.90
7040,Female,0,Yes,Yes,11,Month-to-month,29.60,346.45
7041,Male,1,Yes,No,4,Month-to-month,74.40,306.60
7042,Male,0,No,No,66,Two year,105.65,6844.50

In [39]:
y

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: str

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [40]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [82]:
df.isnull().sum()
X.isnull().sum()

gender            0
SeniorCitizen     0
Partner           0
Dependents        0
tenure            0
Contract          0
MonthlyCharges    0
TotalCharges      0
dtype: int64

In [44]:
df[df['tenure'].isnull()]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

In [45]:
df[df['tenure'] == 0]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,0.0,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,0.0,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,0.0,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,0.0,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,0.0,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,0.0,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,0.0,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,0.0,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,0.0,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,0.0,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,0.0,No

In [18]:
df['TotalCharges'] = df['TotalCharges'].fillna(0)

In [19]:
y

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: str

In [50]:
y = y.map({'Yes': 1, 'No': 0})

In [51]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [52]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,Contract,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,Month-to-month,29.85,29.85
1,Male,0,No,No,34,One year,56.95,1889.50
2,Male,0,No,No,2,Month-to-month,53.85,108.15
3,Male,0,No,No,45,One year,42.30,1840.75
4,Female,0,No,No,2,Month-to-month,70.70,151.65
...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,One year,84.80,1990.50
7039,Female,0,Yes,Yes,72,One year,103.20,7362.90
7040,Female,0,Yes,Yes,11,Month-to-month,29.60,346.45
7041,Male,1,Yes,No,4,Month-to-month,74.40,306.60
7042,Male,0,No,No,66,Two year,105.65,6844.50

In [53]:
col_num = ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [54]:
col_cat = ['gender', 'Partner', 'Dependents', 'Contract']

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [56]:
X_train

,gender,SeniorCitizen,Partner,Dependents,tenure,Contract,MonthlyCharges,TotalCharges
3738,Male,0,No,No,35,Month-to-month,49.20,1701.65
3151,Male,0,Yes,Yes,15,Month-to-month,75.10,1151.55
4860,Male,0,Yes,Yes,13,Two year,40.55,590.35
3867,Female,0,Yes,No,26,Two year,73.50,1905.70
3810,Male,0,Yes,Yes,1,Month-to-month,44.55,44.55
...,...,...,...,...,...,...,...,...
6303,Female,0,Yes,No,71,Two year,109.25,7707.70
6227,Male,0,No,No,2,Month-to-month,46.05,80.35
4673,Female,1,No,No,25,Month-to-month,102.80,2660.20
2710,Female,0,Yes,No,24,One year,20.40,482.80
5639,Male,0,No,No,6,Month-to-month,20.65,109.30

In [57]:
X_test

,gender,SeniorCitizen,Partner,Dependents,tenure,Contract,MonthlyCharges,TotalCharges
437,Male,0,Yes,Yes,72,Two year,114.05,8468.20
2280,Female,1,No,No,8,Month-to-month,100.15,908.55
2235,Female,0,Yes,Yes,41,One year,78.35,3211.20
4460,Male,0,Yes,No,18,Month-to-month,78.20,1468.75
3761,Female,0,Yes,No,72,Two year,82.65,5919.35
...,...,...,...,...,...,...,...,...
5143,Female,0,Yes,Yes,49,One year,87.20,4345.00
4439,Male,0,Yes,Yes,28,Two year,20.30,487.95
3857,Male,0,No,No,5,Month-to-month,20.65,93.55
4758,Female,0,No,No,56,Two year,19.70,1051.90
5613,Female,0,Yes,Yes,72,Two year,70.45,5165.70

In [58]:
y_train

3738    0
3151    0
4860    0
3867    0
3810    0
       ..
6303    0
6227    1
4673    1
2710    0
5639    0
Name: Churn, Length: 5634, dtype: int64

In [59]:
y_test

437     0
2280    0
2235    0
4460    0
3761    0
       ..
5143    0
4439    0
3857    0
4758    0
5613    0
Name: Churn, Length: 1409, dtype: int64

In [60]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessing = ColumnTransformer([
    ('num', StandardScaler(), col_num),
    ('cat', OneHotEncoder(handle_unknown='ignore'), col_cat)
])

In [61]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

pipe = Pipeline([
    ('preprocessing', preprocessing),
    ('model', RandomForestClassifier(random_state=42))
])

In [62]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents',
                                                   'Contract'])])),
                ('model', RandomForestClassifier(random_state=42))])

In [65]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pipe.predict(X_test)))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84      1035
           1       0.57      0.44      0.49       374

    accuracy                           0.76      1409
   macro avg       0.69      0.66      0.67      1409
weighted avg       0.75      0.76      0.75      1409

In [78]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, StratifiedKFold

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

preprocessing = ColumnTransformer([
    ('num', StandardScaler(), col_num),
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), col_cat)
])
# sparse_output=False -> GaussianNB needs a normal (dense) array

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

models = {
    'KNN': (KNeighborsClassifier(), {
        'model__n_neighbors': [5, 15, 25],
        'model__weights': ['uniform', 'distance']
    }),
    'Decision Tree': (DecisionTreeClassifier(random_state=42, class_weight='balanced'), {
        'model__max_depth': [3, 5, 10, None],
        'model__min_samples_leaf': [1, 5, 20]
    }),
    'Random Forest': (RandomForestClassifier(random_state=42, class_weight='balanced'), {
        'model__n_estimators': [100, 200],
        'model__max_depth': [5, 10, None],
        'model__min_samples_leaf': [1, 5]
    }),
}

In [79]:
best_models = {}

for name, (model, params) in models.items():
    pipe = Pipeline([('preprocessing', preprocessing), ('model', model)])

    grid = GridSearchCV(pipe, params, cv=cv, scoring='f1', n_jobs=-1)
    grid.fit(X_train, y_train)

    best_models[name] = grid.best_estimator_
    print(f'{name}: CV F1 = {grid.best_score_:.3f}  {grid.best_params_}')

KNN: CV F1 = 0.540  {'model__n_neighbors': 15, 'model__weights': 'uniform'}
Decision Tree: CV F1 = 0.611  {'model__max_depth': 3, 'model__min_samples_leaf': 1}
Random Forest: CV F1 = 0.616  {'model__max_depth': 10, 'model__min_samples_leaf': 5, 'model__n_estimators': 200}

In [80]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

results = []
for name, model in best_models.items():
    y_pred = model.predict(X_test)
    results.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred),
        'Recall': recall_score(y_test, y_pred),
        'F1': f1_score(y_test, y_pred)
    })

results = pd.DataFrame(results).sort_values('F1', ascending=False)
results

           Model  Accuracy  Precision    Recall        F1
2  Random Forest  0.741661   0.508475  0.802139  0.622407
1  Decision Tree  0.737402   0.503546  0.759358  0.605544
0            KNN  0.766501   0.576792  0.451872  0.506747

In [81]:
import joblib

best_name = results.iloc[0]['Model']
final_model = best_models[best_name]
print('Best model:', best_name)

from sklearn.metrics import classification_report
print(classification_report(y_test, final_model.predict(X_test)))

joblib.dump(final_model, 'churn_best_model.joblib')

Best model: Random Forest
              precision    recall  f1-score   support

           0       0.91      0.72      0.80      1035
           1       0.51      0.80      0.62       374

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.80      0.74      0.76      1409

['churn_best_model.joblib']

# Scenario 01

## Objective

Perusahaan memiliki kenaikan churn rate atau pembatalan yang signifikan, management ingin mengetahui apakah ada cara bagaimana perusahaan bisa melihat pola pembatalan tersebut 

## Problem

Perusahaan membutuhkan agar customer tidak membatalkan subscribtionnya, dan tugas kita sebagai machine learning developer yaitu mengembangkan algortima yang dapat membaca pola untuk customer yang kemungkinan akan batal langganan.

Hypothesis:
Machine Learning Dapat Memprediksi Customer yang Hendak akan batal

---

## Scenario Configuration

### Data Version

Dataset
Name: WA_Fn-UseC_-Telco-Customer-Churn.csv 
Version: 8.82
Source: [Data](https://www.kaggle.com/datasets/blastchar/telco-customer-churn/data)

Feature Engineering
1. Cek kondisi dan informasi data menggunakan df.info() dan df.isnull().sum()
2. mengisi nilai kosong dengan nilai 0
3. feature selection untuk variable x [gender, SeniorCitizen, Partner, Dependents, tenure, Contract,
MonthlyCharges, TotalCharges] dan variable y [churn]
4. target encoding khusus variable y, No -> 0, dan Yes -> 1
5. memilih one-hot encoding untnuk kategori, karena mereka tidak mempunyai order
6. mengaplikasikan standard scaling pada feature numeric

Train/Test Split
Train: 80%
Test: 20%

Random Seed
42

Evaluation Metrics

- Accuracy
- Precision
- Recall
- F1

---

## Model Configuration

each model has run id
| Model | Important Parameters |
|--------|----------------------|
| KNN | n_neighbors = [5, 15, 25] |
| Decision Tree | max_depth = [3, 5, 10, None] |
| Random Forest | n_estimators = [100, 200] dan max_depth = [5, 10, None] |

---

## Experiment Results
Experiment run comparison table with metrics and time
| Model | Parameters | Accuracy | Precision | Recall | F1 |
|---|---|---|---|---|---|
| KNN | n_neigbours=15, weights=uniform | 0.767 | 0.577 | 0.452 | 0.507
| Decision Tree | max_depth=3 | 0.737 | 0.504 | 0.759 | 0.606
| Random Forest | max_depth=10, n_estimator=200 | 0.742 | 0.508 | 0.802 | 0.622

---

## Conclusions
1. KNN kalah karena datanya tidak dilakukan balancing dan KNN pun tidak mempunyai fitur balance, sedangkan decision tree and random forest mempunyainya balancenya
2. Decision Forest kalah dengan random forest karena banyaknya sampling, random forest terdiri dari banyak decision forest yang memiliki sample data yang berbeda
3. akibatnya, dengan 200 "pohon", ditemukan nilai yang paling optimal dan random forest menang

## Decision
Best Model: Random Forest
Output File: churn_best_model.joblib
Selanjutnya: 
- Melakukan deployment
- Mengambil data yang lebih banyak
- Terus maintenance dan improve modelnya

---

Scenario = a controlled set of conditions (e.g., feature engineering method, data split, preprocessing strategy).
Run = a single model trained and evaluated under those conditions.
Master Comparison = a summary that compares scenarios and highlights the best-performing configuration.